### PR TITLE
feat(server): Use uWebSockets

### LINKED ISSUE #61: µWebSockets
Haven't properly evaluated this library yet, but was wondering if you have taken a look at https://github.com/uNetworking/uWebSockets.js ?

### PR DESCRIPTION
**Pull request by maxpain**
- [x] Docs
- [x] Tests
- [x] Backpressure handling
- [ ] Disposability

Closes #61

### CODE REVIEW

**Comment by enisdenjo** [comment]
Lovely! Thanks for doing this. 😄

**Comment by maxpain** [comment]
@enisdenjo Done.

**Comment by maxpain** [comment]
@enisdenjo do you have any questions?

**Comment by enisdenjo** [comment]
I am currently swamped with work and I want to thoroughly check this. So please, bear with me - I will review this PR as soon as I can and will leave questions, if any, on the way.

However, just one remark though - looking at your TODO list, you left the "Backpressure handling" unticked. I wouldn't feel safe merging this until this has been handled.

**Comment by maxpain** [comment]
@enisdenjo I don't know how to handle backpressure properly. Maybe @alexhultman can help.

**Comment by enisdenjo** [comment]
No worries, I'll take care of that once I dig in.

**Comment by enisdenjo** [comment]
Hey hey, sorry for the delay - I was on vacation so I couldnt spend time on this. I am back now and will check this out rather soon!

**Comment by maxpain** [comment]
@enisdenjo any news?

**Comment by enisdenjo** [comment]
Hey hey, sorry for the wait; but, from the looks of it, this PR requires a lot more work. Besides the backpressure handling, the tests have to be rewritten to avoid redundancy and I have to read about uWebSockets a bit more in order to understand the inner workings and then come back to actually doing the review.

 Life is a bit hectic now; still, I hope to have spare time this weekend which I'll invest on this.

**Comment by maxpain** [comment]
@enisdenjo any news? :D

**Comment by MikeAliG** [comment]
Hello everyone! 

First of all, let me thank you for both of your (@maxpain  & @enisdenjo) work on these implementations, this is truly amazing. 

As for this PR, uWebsocket is extremely fast and we have a very large GraphQL server and we are trying to migrate to this package with uWebsocket implementation because of performance gains and this PR so far seems great for the implementation and I was wondering how we can help with merging of this implementation. I'll try to help in any way I can.

Many thanks for all your efforts.

**Comment by enisdenjo** [comment]
@maxpain, I'll be honest - I forgot... Sorry about that! I am starting now.

@MikeAliG thank you for the kind words to @maxpain and me, he really helped with kicking this of! I hope to have this integration done soon. 👍

**Review by enisdenjo — APPROVED** [review]

**Comment by enisdenjo** [comment]
@maxpain, @MikeAliG I would be very grateful if you could try the implementation out and report if it works the way it should. 😄

**Pull request merged**
