### PR TITLE
Base server (class based)

### PR DESCRIPTION
**Pull request by ilijaNL**
Websocket implementation based on ws-graphql protocol without depending on graphql as discussed in https://github.com/enisdenjo/graphql-ws/discussions/461

TODO:
- [ ] Documentation
- [ ] Test for base-server
- [ ] Different use-cases/implementations

### CODE REVIEW

**Review by enisdenjo — COMMENTED** [review]
Oh, I thought you wanted to create a separate library - not have this abstraction here. This is a GQL WS server and it should stay as such without any unnecessary complications or abstractions.

Sorry about any misunderstanding.

**Comment by ilijaNL** [comment]
> 

Yes it is perhaps better, also for leaking (graphql) implementation. However I wonder what you think about this idea/implementation

**Comment by enisdenjo** [comment]
The code is MIT licensed for a reason, I'd love to see what you can make out of it. 😄

**Comment by ilijaNL** [comment]
See https://github.com/enisdenjo/graphql-ws/discussions/461 for follow up

**Pull request closed without merging**
